# Generated by Django 4.1.1 on 2022-09-14 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "middle_name",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "email",
                    models.EmailField(blank=True, editable=False, max_length=100),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, editable=False, max_length=13),
                ),
                (
                    "country_of_residence",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "password",
                    models.CharField(blank=True, editable=False, max_length=40),
                ),
            ],
            options={"ordering": ["-first_name"],},
        ),
    ]
