# Generated by Django 4.1.1 on 2022-09-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country_of_residence",
            field=models.CharField(
                choices=[
                    ("ZW", "Zimbabwe"),
                    ("ZA", "South Africa"),
                    ("KE", "Kenya"),
                    ("UK", "United Kingdom"),
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("AU", "Australia"),
                    ("NZ", "New Zealand"),
                ],
                max_length=100,
            ),
        ),
    ]
