# Generated by Django 4.1.1 on 2022-09-16 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transactions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipients", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("reversed", "Reversed"),
                            ("chargeback", "Chargeback"),
                            ("disputed", "Disputed"),
                            ("expired", "Expired"),
                            ("declined", "Declined"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("voided", "Voided"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("transfer", "Transfer"),
                        ],
                        default="transfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=transactions.models.generate_reference,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient",
                        to="recipients.recipient",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
